incidencetype_index:
    path:     /
    defaults: { _controller: "SystemBackendBundle:IncidenceType:index" }
    methods:  GET

incidencetype_show:
    path:     /{id}/show
    defaults: { _controller: "SystemBackendBundle:IncidenceType:show" }
    methods:  GET

incidencetype_new:
    path:     /new
    defaults: { _controller: "SystemBackendBundle:IncidenceType:new" }
    methods:  [GET, POST]

incidencetype_edit:
    path:     /{id}/edit
    defaults: { _controller: "SystemBackendBundle:IncidenceType:edit" }
    methods:  [GET, POST]

incidencetype_delete:
    path:     /{id}/delete
    defaults: { _controller: "SystemBackendBundle:IncidenceType:delete" }
    methods:  DELETE
