incidence_index:
    path:     /
    defaults: { _controller: "SystemBackendBundle:Incidence:index" }
    methods:  GET

incidence_show:
    path:     /{id}/show
    defaults: { _controller: "SystemBackendBundle:Incidence:show" }
    methods:  GET

incidence_new:
    path:     /new
    defaults: { _controller: "SystemBackendBundle:Incidence:new" }
    methods:  [GET, POST]
    options:  {expose: true}

incidence_edit:
    path:     /{id}/edit
    defaults: { _controller: "SystemBackendBundle:Incidence:edit" }
    methods:  [GET, POST]

incidence_delete:
    path:     /{id}/delete
    defaults: { _controller: "SystemBackendBundle:Incidence:delete" }
    methods:  DELETE

incidence_ajax_get_booking_detail:
    path:   /get_booking_detail
    defaults: { _controller: "SystemBackendBundle:Incidence:getAjaxBookingDetail" }
    options:  {expose: true}

incidence_ajax_get_services_description:
    path:   /get_services_description
    defaults: { _controller: "SystemBackendBundle:Incidence:getAjaxServicesDescription" }
    options:  {expose: true}

incidence_ajax_get_services_description_by_supplier:
    path:   /get_services_description_by_supplier
    defaults: { _controller: "SystemBackendBundle:Incidence:getAjaxServicesDescriptionActionBySupplier" }
    options:  {expose: true}

incidence_ajax_get_booking_suppliers:
    path:   /get_booking_suppliers
    defaults: { _controller: "SystemBackendBundle:Incidence:getAjaxBookingSuppliers" }
    options:  {expose: true}

incidence_ajax_get_booking_services_supplier:
    path:   /get_booking_services_supplier
    defaults: { _controller: "SystemBackendBundle:Incidence:getAjaxServicesBySuppliers" }
    options:  {expose: true}

incidence_ajax_get_booking_client_names:
    path:   /get_booking_client_names
    defaults: { _controller: "SystemBackendBundle:Incidence:getAjaxBookingClientNames" }
    options:  {expose: true}

incidence_ajax_get_booking_person_names:
    path:   /get_booking_person_names
    defaults: { _controller: "SystemBackendBundle:Incidence:getAjaxBookingPersonNames" }
    options:  {expose: true}

incidence_ajax_get_compensation_service:
    path:   /get_compensation_service
    defaults: { _controller: "SystemBackendBundle:Incidence:getAjaxCompensationServices" }
    options:  {expose: true}

incidence_ajax_get_sustitution_services:
    path:   /get_sustitution_services
    defaults: { _controller: "SystemBackendBundle:Incidence:getAjaxSustitutionServices" }
    options:  {expose: true}

#verifica si el booking tiene incidencias asociadas
#incidence_ajax_check_booking:
#    path:   /check_incidences_by_booking
#    defaults: { _controller: "SystemBackendBundle:Incidence:getAjaxCheckIncidencesByBooking" }
#    options:  {expose: true}

#esta ruta es para llamar al metodo q busca las incidencias asociadas al un booking determinado
incidence_ajax_get_incidences_by_booking:
    path:   /get_incidences_by_booking
    defaults: { _controller: "SystemBackendBundle:Incidence:getAjaxIncidencesByBooking" }
    options:  {expose: true}