place_index:
    path:     /
    defaults: { _controller: "SystemBackendBundle:Place:index" }
    methods:  [GET, POST]

#place_show:
#    path:     /{id}/show
#    defaults: { _controller: "SystemBackendBundle:Place:show" }
#    methods:  GET
#
#place_new:
#    path:     /new
#    defaults: { _controller: "SystemBackendBundle:Place:new" }
#    methods:  [GET, POST]

place_edit:
    path:     /{id}/edit
    defaults: { _controller: "SystemBackendBundle:Place:edit" }
    methods:  [GET, POST]

place_delete:
    path:     /{id}/delete
    defaults: { _controller: "SystemBackendBundle:Place:delete" }
#    methods:  DELETE
