servicetype_index:
    path:     /
    defaults: { _controller: "SystemBackendBundle:ServiceType:index" }
    methods:  [GET, POST]
#
#servicetype_show:
#    path:     /{id}/show
#    defaults: { _controller: "SystemBackendBundle:ServiceType:show" }
#    methods:  GET
#
#servicetype_new:
#    path:     /new
#    defaults: { _controller: "SystemBackendBundle:ServiceType:new" }
#    methods:  [GET, POST]

servicetype_edit:
    path:     /{id}/edit
    defaults: { _controller: "SystemBackendBundle:ServiceType:edit" }
    methods:  [GET, POST]

servicetype_delete:
    path:     /{id}/delete
    defaults: { _controller: "SystemBackendBundle:ServiceType:delete" }
#    methods:  DELETE
