system_backend_homepage:
    resource: "@SystemBackendBundle/Resources/config/routing/department.yml"
    prefix:   /department

system_backend_category:
    resource: "@SystemBackendBundle/Resources/config/routing/category.yml"
    prefix:   /category


system_backend_subcategory:
    resource: "@SystemBackendBundle/Resources/config/routing/subcategory.yml"
    prefix:   /subcategory

system_backend_itemtype:
    resource: "@SystemBackendBundle/Resources/config/routing/itemtype.yml"
    prefix:   /itemtype

system_backend_incidencetype:
    resource: "@SystemBackendBundle/Resources/config/routing/incidencetype.yml"
    prefix:   /incidencetype

system_backend_servicetype:
    resource: "@SystemBackendBundle/Resources/config/routing/servicetype.yml"
    prefix:   /servicetype

system_backend_incidence:
    resource: "@SystemBackendBundle/Resources/config/routing/incidence.yml"
    prefix:   /incidence

system_backend_place:
    resource: "@SystemBackendBundle/Resources/config/routing/place.yml"
    prefix:   /place

system_backend_person:
    resource: "@SystemBackendBundle/Resources/config/routing/person.yml"
    prefix:   /person