system_tp:
    resource: "@SystemTPBundle/Resources/config/routing.yml"
    prefix:   /

system_claim:
    resource: "@SystemClaimBundle/Resources/config/routing.yml"
    prefix:   /

system_reportes:
    resource: "@SystemReportesBundle/Resources/config/routing.yml"
    prefix:   /

system_backend:
    resource: "@SystemBackendBundle/Resources/config/routing.yml"
    prefix:   /backend

system_incidence:
    resource: "@SystemIncidenceBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
