<?php

namespace System\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Incidence_PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Incidence_PersonRepository extends EntityRepository
{
}
